<?php

namespace AppBundle\Repository;

/**
 * HireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HireRepository extends \Doctrine\ORM\EntityRepository
{
}
